# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Error(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, code: int=None, massage: str=None):  # noqa: E501
        """Error - a model defined in Swagger

        :param code: The code of this Error.  # noqa: E501
        :type code: int
        :param massage: The massage of this Error.  # noqa: E501
        :type massage: str
        """
        self.swagger_types = {
            'code': int,
            'massage': str
        }

        self.attribute_map = {
            'code': 'code',
            'massage': 'massage'
        }
        self._code = code
        self._massage = massage

    @classmethod
    def from_dict(cls, dikt) -> 'Error':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Error of this Error.  # noqa: E501
        :rtype: Error
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> int:
        """Gets the code of this Error.


        :return: The code of this Error.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this Error.


        :param code: The code of this Error.
        :type code: int
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def massage(self) -> str:
        """Gets the massage of this Error.


        :return: The massage of this Error.
        :rtype: str
        """
        return self._massage

    @massage.setter
    def massage(self, massage: str):
        """Sets the massage of this Error.


        :param massage: The massage of this Error.
        :type massage: str
        """

        self._massage = massage
